version: '3.8'

services:
  php:
    build: ../php
    volumes:
      - ../public:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schooldb
    volumes:
      - db_data:/var/lib/mysql
      - ../database/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  db_data:
